apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-deployment
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-deployment
    spec:
      containers:
      - image: 192.168.44.44:8082/docker_registry/frontend:latest
        name: frontend
        env:
          - name: BACKEND_URL
            value: http://backend-service:5001
        ports:
        - containerPort: 5000
        resources: {}
      imagePullSecrets:
        - name: regcred
status: {}
