apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: frontend
    repoURL: 'https://github.com/kwaiga8/ArgoCD.git'
    targetRevision: HEAD
  project: default
metadata:
  name: frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=192.168.44.44:8082/docker_registry/frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd